services:
  redis:
    image: redis:alpine
    ports: 
      - '$REDIS_PORT:$REDIS_PORT'
    expose:
       - '$REDIS_PORT'
    container_name: sso-app-redis
  app:
    build:
      context: .
      dockerfile: DockerFile
      target: deploy
    env_file:
      - .env
    container_name: sso-app
    depends_on:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
